config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
  resources :tweets
  resources :users, only: [:show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.page(params[:page]).per(8).order('created_at DESC')
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])
    @user = @tweet.user
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    Tweet.create(title: tweet_params[:title], content: tweet_params[:content], user_id: current_user.id)
    redirect_to action: :index
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy if tweet.user_id == current_user.id
    redirect_to action: :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(current_user)
    @tweets = @user.tweets.order("created_at DESC")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MiniBlog
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .header
      .header__bar
        %h1.header__bar__name
          = link_to root_path do
            mini-blog
        .header__bar__sign
          - if user_signed_in?
            .header__bar__sign__out.btn.btn-primary
              = link_to 'ログアウト', destroy_user_session_path, class: 'btn-color', method: :delete
            .header__bar__sign__page.btn.btn-primary
              = link_to 'マイページ', "/users/current_user.id", class: 'btn-color'
            .header__bar__sign__new.btn.btn-primary
              = link_to '新規投稿', new_tweet_path, class: 'btn-color'
          - else
            .header__bar__sign__in.btn.btn-primary
              = link_to 'サインイン', new_user_session_path, class: 'btn-color'
            .header__bar__sign__new.btn.btn-primary
              = link_to '新規登録', new_user_registration_path, class: 'btn-color'
    = yield

app/views/tweets/_form.html.haml
= form_for @tweet do |f|
  - if @tweet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:"
      %ul
        - @tweet.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/tweets/edit.html.haml
%h1 Editing tweet

= render 'form'

= link_to 'Show', @tweet
\|
= link_to 'Back', tweets_path

app/views/tweets/index.html.haml
.main-content-body
  .contents.text-center
    %b 新着記事一覧
    - @tweets.each do |tweet|
      .contents__main
        %ul
          %li.more_list
            = link_to "#{tweet.title}：投稿者#{tweet.user.name}(#{tweet.created_at.strftime('%m/%d')})", "/tweets/#{tweet.id}", class: "list-box"
    = paginate @tweets

app/views/tweets/new.html.haml
%h1 New tweet

= render 'form'


= link_to 'Back', tweets_path

app/views/tweets/show.html.haml
.wrapper

  = render 'users/side_bar'

  .main-content
    .main-content__title
      = @tweet.title
    .main-content__content
      = @tweet.content

  .bottom-content
    .bottom-content__back.btn.btn-primary
      = link_to '戻る', tweets_path, class: 'btn-color'
    - if current_user.id == @tweet.user_id
      .bottom-content__edit.btn.btn-primary
        = link_to '更新', edit_tweet_path(@tweet), class: 'btn-color'
      .bottom-content__delete.btn.btn-primary
        = link_to '削除', tweet_path, method: :delete, class: 'btn-color'

.another
  - unless current_user.id == @tweet.user_id
    .another-info
      = @tweet.user.name
      %b の他の記事
      .another-info__tweets
      - @user.tweets.reverse_each do |tweet|
        .another-info__tweets__link
          =link_to "/tweets/#{tweet.id}", class:"tweet-link" do
            .another-info__tweets__link__title
              = tweet.title

app/views/users/_side_bar.html.haml
.chat-side
  .side-header
    .side-header__box
      %h1.side-header__box__name
        = current_user.name
        %b のマイページ
    %ul.side-header__icons
      %li.list
        = link_to edit_user_registration_path do
          %i.fa.fa-pencil-square-o
  .groups
    .groups__title
      = current_user.name
      %b の投稿記事一覧
    .groups__content
      - current_user.tweets.reverse_each do |tweet|
        .groups__content__title
          =link_to "/tweets/#{tweet.id}" do
            .groups__content__title__main
            = tweet.title

app/views/users/show.html.haml
.wrapper

  = render 'side_bar'